<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Interactive Timeline & Calendar') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    
                    <div class="mb-6 flex justify-between items-center bg-gray-50 p-4 rounded-lg shadow-inner">
                        <button id="prevBtn" class="px-4 py-2 bg-white border border-gray-300 rounded shadow hover:bg-gray-100">&larr; Previous</button>
                        <h3 id="monthDisplay" class="text-2xl font-bold text-gray-700"></h3>
                        <button id="nextBtn" class="px-4 py-2 bg-white border border-gray-300 rounded shadow hover:bg-gray-100">Next &rarr;</button>
                    </div>

                    <div class="w-full overflow-x-auto">
                        <table class="w-full table-fixed border-collapse bg-white shadow-sm border border-gray-200">
                            <thead>
                                <tr class="bg-gray-200 text-gray-600 uppercase text-xs sm:text-sm leading-normal">
                                    <th class="py-3 px-2 border w-1/7 text-center">Sun</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Mon</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Tue</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Wed</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Thu</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Fri</th>
                                    <th class="py-3 px-2 border w-1/7 text-center">Sat</th>
                                </tr>
                            </thead>
                            <tbody id="calendarBody" class="text-gray-600 text-sm font-light">
                                <!-- Calendar Generated by JS -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Offline Vanilla JS Calendar Engine -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const date = new Date();
            let currentMonth = date.getMonth();
            let currentYear = date.getFullYear();

            // Inject Blade JSON variables for events processing locally
            const events = @json($events); 
            
            const monthDisplay = document.getElementById('monthDisplay');
            const calendarBody = document.getElementById('calendarBody');
            const prevBtn = document.getElementById('prevBtn');
            const nextBtn = document.getElementById('nextBtn');

            const months = [
                'January', 'February', 'March', 'April', 'May', 'June', 
                'July', 'August', 'September', 'October', 'November', 'December'
            ];

            function renderCalendar() {
                calendarBody.innerHTML = '';
                monthDisplay.innerText = `${months[currentMonth]} ${currentYear}`;

                const firstDay = new Date(currentYear, currentMonth, 1).getDay();
                const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();

                let d = 1;
                for (let i = 0; i < 6; i++) {
                    const row = document.createElement('tr');
                    let hasDays = false;

                    for (let j = 0; j < 7; j++) {
                        const cell = document.createElement('td');
                        cell.className = 'border py-2 px-1 align-top h-24 sm:h-32 transition duration-300 ease max-w-0';

                        if (i === 0 && j < firstDay) {
                            // Empty cells before month starts
                            cell.classList.add('bg-gray-50');
                            row.appendChild(cell);
                        } else if (d > daysInMonth) {
                            // Empty cells after month ends
                            cell.classList.add('bg-gray-50');
                            row.appendChild(cell);
                        } else {
                            hasDays = true;
                            const isToday = d === date.getDate() && currentMonth === date.getMonth() && currentYear === date.getFullYear();
                            
                            // Day Number Container
                            const numDiv = document.createElement('div');
                            numDiv.className = `text-right mb-1 ${isToday ? 'font-bold text-blue-600 bg-blue-100 rounded-full inline-block w-6 h-6 text-center float-right' : 'text-gray-500 float-right mr-1'}`;
                            numDiv.innerText = d;
                            
                            const clearFix = document.createElement('div');
                            clearFix.className = 'clear-both mb-1';

                            cell.appendChild(numDiv);
                            cell.appendChild(clearFix);
                            cell.classList.add('hover:bg-blue-50', 'hover:cursor-pointer');

                            // Look up events for this day
                            // Format: YYYY-MM-DD
                            const mStr = String(currentMonth + 1).padStart(2, '0');
                            const dStr = String(d).padStart(2, '0');
                            const dateStr = `${currentYear}-${mStr}-${dStr}`;

                            const dayEvents = events.filter(e => e.date === dateStr);
                            
                            const eventsContainer = document.createElement('div');
                            eventsContainer.className = 'flex flex-col gap-1 overflow-y-auto max-h-16 sm:max-h-24 no-scrollbar';

                            dayEvents.forEach(ev => {
                                const evDiv = document.createElement('div');
                                const bgColors = {
                                    'staff_in': 'bg-green-100 text-green-800 border-green-200',
                                    'visitor_in': 'bg-purple-100 text-purple-800 border-purple-200',
                                };
                                const bg = bgColors[ev.type] || 'bg-gray-100 border-gray-200 text-gray-800';
                                
                                evDiv.className = `text-[10px] sm:text-xs p-1 rounded border truncate ${bg}`;
                                evDiv.innerText = ev.title;
                                evDiv.title = ev.title; // hover tooltip
                                
                                eventsContainer.appendChild(evDiv);
                            });

                            cell.appendChild(eventsContainer);
                            
                            // Make whole cell clickable to go to reports for that date
                            cell.onclick = () => {
                                window.location.href = `/reports?date=${dateStr}`;
                            };

                            row.appendChild(cell);
                            d++;
                        }
                    }

                    if (hasDays) {
                        calendarBody.appendChild(row);
                    }
                }
            }

            prevBtn.addEventListener('click', () => {
                currentMonth--;
                if (currentMonth < 0) {
                    currentMonth = 11;
                    currentYear--;
                }
                renderCalendar();
            });

            nextBtn.addEventListener('click', () => {
                currentMonth++;
                if (currentMonth > 11) {
                    currentMonth = 0;
                    currentYear++;
                }
                renderCalendar();
            });

            // Initial render
            renderCalendar();
        });
    </script>

    <style>
        .no-scrollbar::-webkit-scrollbar {
            display: none;
        }
        .no-scrollbar {
            -ms-overflow-style: none;  /* IE and Edge */
            scrollbar-width: none;  /* Firefox */
        }
    </style>
</x-app-layout>
